import pandas as pd

def prepare(df):
    before_rows = len(df)
    df = df.drop_duplicates()
    after_rows = len(df)
    print("Removed " + str(before_rows - after_rows) + " duplicate rows!")
    df = df.fillna(df.mean(numeric_only=True))
    text_cols = df.select_dtypes(include='object').columns
    df[text_cols] = df[text_cols].fillna("Unknown")
    print("Your data is ready!")
    return df

def report(df):
    print("==============================")
    print("       DATANIX REPORT       ")
    print("==============================")
    print("Total Rows    : " + str(df.shape[0]))
    print("Total Columns : " + str(df.shape[1]))
    print("------------------------------")
    print("Missing Values:")
    print(str(df.isnull().sum()))
    print("------------------------------")
    print("Duplicate Rows: " + str(df.duplicated().sum()))
    print("------------------------------")
    print("Column Types:")
    print(str(df.dtypes))
    print("------------------------------")
    print("Basic Statistics:")
    print(str(df.describe()))
    print("==============================")
    print("Report generated by datanix!")
    print("==============================")

def check(df):
    print("CHECKING DATA PROBLEMS")
    print("Missing values  : " + str(df.isnull().sum().sum()))
    print("Duplicate rows  : " + str(df.duplicated().sum()))
    print("Total columns   : " + str(len(df.columns)))
    print("Total rows      : " + str(len(df)))
    if df.isnull().sum().sum() == 0 and df.duplicated().sum() == 0:
        print("No problems found!")
    else:
        print("Problems found! Run prepare() to fix!")

def fix(df, strategy="mean"):
    print("FIXING YOUR DATA...")
    df = df.drop_duplicates()
    if strategy == "mean":
        df = df.fillna(df.mean(numeric_only=True))
    elif strategy == "median":
        df = df.fillna(df.median(numeric_only=True))
    elif strategy == "mode":
        df = df.fillna(df.mode().iloc[0])
    print("Data is clean!")
    return df
    
def visualize(df):
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle("DATANIX VISUAL REPORT", fontsize=16)

    # Chart 1 - Missing Values
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if len(missing) > 0:
        axes[0].bar(missing.index, missing.values, color="red")
        axes[0].set_title("Missing Values")
        axes[0].set_xlabel("Columns")
        axes[0].set_ylabel("Count")
    else:
        axes[0].text(0.5, 0.5, "No Missing Values!", 
                    ha="center", va="center")
        axes[0].set_title("Missing Values")

    # Chart 2 - Column Types
    types = df.dtypes.astype(str).value_counts()
    axes[1].pie(types.values, labels=types.index, autopct="%1.1f%%")
    axes[1].set_title("Column Types")

    # Chart 3 - Numeric Distribution
    numeric_cols = df.select_dtypes(include="number").columns
    if len(numeric_cols) > 0:
        df[numeric_cols[0]].hist(ax=axes[2], color="blue", bins=20)
        axes[2].set_title("Distribution of " + numeric_cols[0])
        axes[2].set_xlabel("Value")
        axes[2].set_ylabel("Count")

    plt.tight_layout()
    plt.show()
    print("Visualization complete!")
    